### ISSUE TITLE
Version 4.1 Shipping Soon

### ISSUE THREAD

**Issue by brianjrobertson** [holacracyone/Holacracy-Constitution#21]
Hi Folks - I have two outstanding items to address on my list, hopefully tomorrow, and then I think we're ready to ship the head revision as v4.1 (and then begin considering changes for v5.0).  Does anyone know of any other changes that would be good to consider for v4.1?  If so, please share now, as we're targeting end of week to have v4.1 finalized!

Also, if anyone is so inclined to double-check some of my recent changes, I'd appreciate it...
- Brian

**Comment by MiekeByerley** [comment]
Okay, I have raised all the ones I was talking about earlier on sorry for the volume.

**Comment by brianjrobertson** [comment]
Last call for feedback or pull requests before we officially stamp the head revision as v4.1 and ship it...

**Comment by MiekeByerley** [comment]
That was an epic dash for the finish line Brian. :+1:

**Comment by diederickjanse** [comment]
I've done all the finetuning I'm going to do on this version, I say ship it! (yay)

**Comment by julianeroell** [comment]
I have a few more changes coming up (that is: tonight, Sunday evening CET) - all relatively simple language simplifications and fixes, but valuable nevertheless. I will submit a pull request when I am ready with all of them, but if you are in a hurry, do pull them in from https://github.com/martinroell/Holacracy-Constitution/commits/master already!

**Comment by brianjrobertson** [comment]
Hey Martin - We are actively working on publishing v4.1 right at this moment, so unfortunately we won't be able to consider anything for that if it isn't submitted _really_ soon...

**Comment by brianjrobertson** [comment]
... but we're still messing with general web formatting right now, so you still have at least a little time.  Also note it's probably easier to submit multiple pull requests, so that if I need to reject one change I don't have to throw out all of them with it...

**Comment by julianeroell** [comment]
I have only just learnt how to branch (yay), so this time, it's still lumped together. (Github automatically lumps all new commits to a single branch together in the same pull request, so one must branch, if the request shall be separate.) I have committed my current changes to my repo and sent the pull request. (https://github.com/holacracyone/Holacracy-Constitution/pull/30)

**Comment by brianjrobertson** [comment]
Hey Martin - I saw your pull request, but now it appears to be withdrawn/deleted, and your entire fork seems to be deleted as well, so I can't pull from it manually either, or even review the changes any more - I just get a 404 error from github when I try to hit any of your pages.  Not sure what happened there, but hope you didn't lose the work - it looked good!  I do still have some of it open in browser tabs, so I'm going to go ahead and manually recreate & submit some of the changes now, before we ship v4.1.

**Comment by julianeroell** [comment]
I have a message here (on github.com) that says:

> One of our mostly harmless robots seems to think you are not a human.
> Because of that, it's hidden your profile from the public. If you really are human, please contact support to have your profile reinstated.

I have contacted support already.

**Comment by julianeroell** [comment]
(I can still access all of my work, and work with the repository as usual. It seems that it's just hidden to all other people at the moment.)

**Comment by brianjrobertson** [comment]
Okay, I've integrated what I could still see of Martin's feedback (thanks!), and I'm calling this done so @ocompagne can publish it; of course we can always consider more for the next version as well.

**Comment by julianeroell** [comment]
(My account has been reinstated.)

**Comment by brianjrobertson** [comment]
Okay, I've integrated a more of Martin's changes, and now I'm calling v4.1 officially done; it'll be on our website shortly...
